[package]
name = "kuwnote"
version = "2.0.0"
description = "Kuwnote - Modern modular workspace note-taking app"
authors = ["ruject"]
edition = "2021"

[lib]
name = "kuwnote_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
